### ISSUE TITLE
Building fails

### ISSUE THREAD

**Issue by SlimePharaoh** [MCMrARM/mcpelauncher-linux#145]
For some reasons, the make command drops this error:

peti@tata-pc:~/mcpelauncher-linux$ make
Scanning dependencies of target mcpelauncher
[  4%] Building C object CMakeFiles/mcpelauncher.dir/hybris/src/cache.c.o
/home/peti/mcpelauncher-linux/hybris/src/cache.c: In function ‘cache_update’:
/home/peti/mcpelauncher-linux/hybris/src/cache.c:105:10: warning: ‘return’ with a value, in function returning void
   return NULL;
          ^
[  9%] Building C object CMakeFiles/mcpelauncher.dir/hybris/src/dlfcn.c.o
/home/peti/mcpelauncher-linux/hybris/src/dlfcn.c: In function ‘hybris_dlerror’:
/home/peti/mcpelauncher-linux/hybris/src/dlfcn.c:47:12: warning: return discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
     return android_dlerror();
            ^
[ 13%] Building C object CMakeFiles/mcpelauncher.dir/hybris/src/hooks.c.o
/home/peti/mcpelauncher-linux/hybris/src/hooks.c:24:0: warning: "_GNU_SOURCE" redefined
 #define _GNU_SOURCE
 ^
<command-line>:0:0: note: this is the location of the previous definition
/home/peti/mcpelauncher-linux/hybris/src/hooks.c: In function ‘my_pthread_attr_setstackaddr’:
/home/peti/mcpelauncher-linux/hybris/src/hooks.c:297:5: warning: ‘pthread_attr_setstackaddr’ is deprecated [-Wdeprecated-declarations]
     return pthread_attr_setstackaddr(realattr, stack_addr);
     ^
In file included from /home/peti/mcpelauncher-linux/hybris/src/hooks.c:34:0:
/usr/include/pthread.h:363:12: note: declared here
 extern int pthread_attr_setstackaddr (pthread_attr_t *__attr,
            ^
/home/peti/mcpelauncher-linux/hybris/src/hooks.c: In function ‘my_pthread_attr_getstackaddr’:
/home/peti/mcpelauncher-linux/hybris/src/hooks.c:303:5: warning: ‘pthread_attr_getstackaddr’ is deprecated [-Wdeprecated-declarations]
     return pthread_attr_getstackaddr(realattr, stack_addr);
     ^
In file included from /home/peti/mcpelauncher-linux/hybris/src/hooks.c:34:0:
/usr/include/pthread.h:355:12: note: declared here
 extern int pthread_attr_getstackaddr (const pthread_attr_t *__restrict
            ^
/home/peti/mcpelauncher-linux/hybris/src/hooks.c: In function ‘hybris_set_realrwlock’:
/home/peti/mcpelauncher-linux/hybris/src/hooks.c:844:20: warning: comparison between pointer and integer
     if (realrwlock <= ANDROID_TOP_ADDR_VALUE_RWLOCK) {
                    ^
/home/peti/mcpelauncher-linux/hybris/src/hooks.c: In function ‘my_clearerr’:
/home/peti/mcpelauncher-linux/hybris/src/hooks.c:974:29: warning: passing argument 1 of ‘_get_actual_fp’ from incompatible pointer type [-Wincompatible-pointer-types]
     clearerr(_get_actual_fp(fp));
                             ^
/home/peti/mcpelauncher-linux/hybris/src/hooks.c:959:14: note: expected ‘struct aFILE *’ but argument is of type ‘FILE * {aka struct _IO_FILE *}’
 static FILE *_get_actual_fp(struct aFILE *fp)
              ^
/home/peti/mcpelauncher-linux/hybris/src/hooks.c: In function ‘my_fdopen’:
/home/peti/mcpelauncher-linux/hybris/src/hooks.c:991:25: warning: passing argument 1 of ‘fdopen’ makes integer from pointer without a cast [-Wint-conversion]
     FILE* file = fdopen(filename, mode);
                         ^
In file included from /home/peti/mcpelauncher-linux/hybris/src/hooks.c:25:0:
/usr/include/stdio.h:306:14: note: expected ‘int’ but argument is of type ‘const char *’
 extern FILE *fdopen (int __fd, const char *__modes) __THROW __wur;
              ^
/home/peti/mcpelauncher-linux/hybris/src/hooks.c: In function ‘my_scandirat’:
/home/peti/mcpelauncher-linux/hybris/src/hooks.c:1365:67: warning: passing argument 4 of ‘qsort’ from incompatible pointer type [-Wincompatible-pointer-types]
             qsort(result, nItems, sizeof(struct bionic_dirent *), compar);
                                                                   ^
In file included from /home/peti/mcpelauncher-linux/hybris/src/hooks.c:29:0:
/usr/include/stdlib.h:764:13: note: expected ‘__compar_fn_t {aka int (*)(const void *, const void *)}’ but argument is of type ‘int (*)(const struct bionic_dirent **, const struct bionic_dirent **)’
 extern void qsort (void *__base, size_t __nmemb, size_t __size,
             ^
/home/peti/mcpelauncher-linux/hybris/src/hooks.c: In function ‘my_system_property_get’:
/home/peti/mcpelauncher-linux/hybris/src/hooks.c:1446:28: warning: passing argument 2 of ‘property_get’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  return property_get(name, value, NULL);
                            ^
In file included from /home/peti/mcpelauncher-linux/hybris/src/hooks.c:57:0:
/home/peti/mcpelauncher-linux/hybris/src/../include/hybris/properties.h:51:6: note: expected ‘char *’ but argument is of type ‘const char *’
  int property_get(const char *key, char *value, const char *default_value);
      ^
/home/peti/mcpelauncher-linux/hybris/src/hooks.c: In function ‘convert_addrinfo’:
/home/peti/mcpelauncher-linux/hybris/src/hooks.c:1485:23: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
         ares->ai_next = convert_addrinfo(res->ai_next);
                       ^
[ 18%] Building C object CMakeFiles/mcpelauncher.dir/hybris/src/hooks_shm.c.o
/home/peti/mcpelauncher-linux/hybris/src/hooks_shm.c:21:0: warning: "_GNU_SOURCE" redefined
 #define _GNU_SOURCE
 ^
<command-line>:0:0: note: this is the location of the previous definition
/home/peti/mcpelauncher-linux/hybris/src/hooks_shm.c: In function ‘_hybris_shm_init’:
/home/peti/mcpelauncher-linux/hybris/src/hooks_shm.c:140:21: warning: implicit declaration of function ‘memset’ [-Wimplicit-function-declaration]
                     memset((void*)_hybris_shm_data, 0, size_to_map);
                     ^
/home/peti/mcpelauncher-linux/hybris/src/hooks_shm.c:140:21: warning: incompatible implicit declaration of built-in function ‘memset’
/home/peti/mcpelauncher-linux/hybris/src/hooks_shm.c:140:21: note: include ‘<string.h>’ or provide a declaration of ‘memset’
[ 22%] Building C object CMakeFiles/mcpelauncher.dir/hybris/src/logging.c.o
[ 27%] Building C object CMakeFiles/mcpelauncher.dir/hybris/src/properties.c.o
/home/peti/mcpelauncher-linux/hybris/src/properties.c:28:0: warning: "__USE_GNU" redefined
 #define __USE_GNU
 ^
In file included from /usr/include/string.h:25:0,
                 from /home/peti/mcpelauncher-linux/hybris/src/properties.c:22:
/usr/include/features.h:325:0: note: this is the location of the previous definition
 # define __USE_GNU 1
 ^
[ 31%] Building C object CMakeFiles/mcpelauncher.dir/hybris/src/strlcpy.c.o
[ 36%] Building C object CMakeFiles/mcpelauncher.dir/hybris/src/sysconf.c.o
[ 40%] Building C object CMakeFiles/mcpelauncher.dir/hybris/src/jb/dlfcn.c.o
/home/peti/mcpelauncher-linux/hybris/src/jb/dlfcn.c:16:0: warning: "_GNU_SOURCE" redefined
 #define _GNU_SOURCE
 ^
<command-line>:0:0: note: this is the location of the previous definition
/home/peti/mcpelauncher-linux/hybris/src/jb/dlfcn.c: In function ‘android_dladdr’:
/home/peti/mcpelauncher-linux/hybris/src/jb/dlfcn.c:139:9: warning: implicit declaration of function ‘memset’ [-Wimplicit-function-declaration]
         memset(info, 0, sizeof(Dl_info));
         ^
/home/peti/mcpelauncher-linux/hybris/src/jb/dlfcn.c:139:9: warning: incompatible implicit declaration of built-in function ‘memset’
/home/peti/mcpelauncher-linux/hybris/src/jb/dlfcn.c:139:9: note: include ‘<string.h>’ or provide a declaration of ‘memset’
[ 45%] Building C object CMakeFiles/mcpelauncher.dir/hybris/src/jb/linker.c.o
/home/peti/mcpelauncher-linux/hybris/src/jb/linker.c: In function ‘alloc_info’:
/home/peti/mcpelauncher-linux/hybris/src/jb/linker.c:287:5: warning: implicit declaration of function ‘strlcpy’ [-Wimplicit-function-declaration]
     strlcpy((char*) si->name, name, sizeof(si->name));
     ^
/home/peti/mcpelauncher-linux/hybris/src/jb/linker.c: In function ‘reloc_library’:
/home/peti/mcpelauncher-linux/hybris/src/jb/linker.c:1330:24: warning: implicit declaration of function ‘get_hooked_symbol’ [-Wimplicit-function-declaration]
             sym_addr = get_hooked_symbol(sym_name);
                        ^
/home/peti/mcpelauncher-linux/hybris/src/jb/linker.c:1331:26: warning: comparison between pointer and integer
             if (sym_addr != NULL) {
                          ^
/home/peti/mcpelauncher-linux/hybris/src/jb/linker.c:1337:25: warning: comparison between pointer and integer
             if(sym_addr == NULL)
                         ^
[ 50%] Building C object CMakeFiles/mcpelauncher.dir/hybris/src/jb/linker_environ.c.o
[ 54%] Building C object CMakeFiles/mcpelauncher.dir/hybris/src/jb/linker_format.c.o
[ 59%] Building C object CMakeFiles/mcpelauncher.dir/hybris/src/jb/rt.c.o
[ 63%] Building C object CMakeFiles/mcpelauncher.dir/eglut/eglut.c.o
/home/peti/mcpelauncher-linux/eglut/eglut.c: In function ‘eglutCreateWindow’:
/home/peti/mcpelauncher-linux/eglut/eglut.c:324:22: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
     win->keyboard_cb = _eglutDefaultKeyboard;
                      ^
[ 68%] Building C object CMakeFiles/mcpelauncher.dir/eglut/eglut_x11.c.o
[ 72%] Building CXX object CMakeFiles/mcpelauncher.dir/src/main.cpp.o
/home/peti/mcpelauncher-linux/src/main.cpp: In function ‘int main(int, char**)’:
/home/peti/mcpelauncher-linux/src/main.cpp:354:76: warning: converting from ‘void (LinuxHttpRequestInternal::*)()’ to ‘void*’ [-Wpmf-conversions]
 linuxHttpRequestInternalVtable[0] = (void*) &LinuxHttpRequestInternal::destroy;
                                                                        ^
/home/peti/mcpelauncher-linux/src/main.cpp:355:76: warning: converting from ‘void (LinuxHttpRequestInternal::*)()’ to ‘void*’ [-Wpmf-conversions]
 linuxHttpRequestInternalVtable[1] = (void*) &LinuxHttpRequestInternal::destroy;
                                                                        ^
[ 77%] Building CXX object CMakeFiles/mcpelauncher.dir/src/common.cpp.o
[ 81%] Building CXX object CMakeFiles/mcpelauncher.dir/src/hook.cpp.o
[ 86%] Building ASM object CMakeFiles/mcpelauncher.dir/src/amdfix.s.o
[ 90%] Building CXX object CMakeFiles/mcpelauncher.dir/src/LinuxAppPlatform.cpp.o
/home/peti/mcpelauncher-linux/src/LinuxAppPlatform.cpp: In static member function ‘static void LinuxAppPlatform::initVtable(void*)’:
/home/peti/mcpelauncher-linux/src/LinuxAppPlatform.cpp:66:104: warning: converting from ‘std::string (LinuxAppPlatform::*)() {aka std::basic_string<char> (LinuxAppPlatform::*)()}’ to ‘void*’ [-Wpmf-conversions]
 ZNK19AppPlatform_android10getDataUrlEv", (void*) &LinuxAppPlatform::getDataUrl)
                                                                     ^
/home/peti/mcpelauncher-linux/src/LinuxAppPlatform.cpp:67:108: warning: converting from ‘std::string (LinuxAppPlatform::*)() {aka std::basic_string<char> (LinuxAppPlatform::*)()}’ to ‘void*’ [-Wpmf-conversions]
 9AppPlatform_android14getUserDataUrlEv", (void*) &LinuxAppPlatform::getUserData
                                                                     ^
/home/peti/mcpelauncher-linux/src/LinuxAppPlatform.cpp:68:107: warning: converting from ‘std::string (LinuxAppPlatform::*)() {aka std::basic_string<char> (LinuxAppPlatform::*)()}’ to ‘void*’ [-Wpmf-conversions]
 9AppPlatform_android14getPackagePathEv", (void*) &LinuxAppPlatform::getPackageP
                                                                     ^
/home/peti/mcpelauncher-linux/src/LinuxAppPlatform.cpp:69:101: warning: converting from ‘void (LinuxAppPlatform::*)()’ to ‘void*’ [-Wpmf-conversions]
  "_ZN11AppPlatform16hideMousePointerEv", (void*) &LinuxAppPlatform::hideMousePo
                                                                     ^
/home/peti/mcpelauncher-linux/src/LinuxAppPlatform.cpp:70:101: warning: converting from ‘void (LinuxAppPlatform::*)()’ to ‘void*’ [-Wpmf-conversions]
  "_ZN11AppPlatform16showMousePointerEv", (void*) &LinuxAppPlatform::showMousePo
                                                                     ^
/home/peti/mcpelauncher-linux/src/LinuxAppPlatform.cpp:71:104: warning: converting from ‘void (LinuxAppPlatform::*)()’ to ‘void*’ [-Wpmf-conversions]
 ZN19AppPlatform_android11swapBuffersEv", (void*) &LinuxAppPlatform::swapBuffers
                                                                     ^
/home/peti/mcpelauncher-linux/src/LinuxAppPlatform.cpp:72:109: warning: converting from ‘const string& (LinuxAppPlatform::*)() {aka const std::basic_string<char>& (LinuxAppPlatform::*)()}’ to ‘void*’ [-Wpmf-conversions]
 AppPlatform_android15getSystemRegionEv", (void*) &LinuxAppPlatform::getSystemRe
                                                                     ^
/home/peti/mcpelauncher-linux/src/LinuxAppPlatform.cpp:73:118: warning: converting from ‘bool (LinuxAppPlatform::*)()’ to ‘void*’ [-Wpmf-conversions]
 m_android25getGraphicsTearingSupportEv", (void*) &LinuxAppPlatform::getGraphics
                                                                     ^
/home/peti/mcpelauncher-linux/src/LinuxAppPlatform.cpp:74:123: warning: converting from ‘void (LinuxAppPlatform::*)(ImagePickingCallback&)’ to ‘void*’ [-Wpmf-conversions]
 roid9pickImageER20ImagePickingCallback", (void*) &LinuxAppPlatform::pickImage);
                                                                     ^
/home/peti/mcpelauncher-linux/src/LinuxAppPlatform.cpp:75:112: warning: converting from ‘void (LinuxAppPlatform::*)(FilePickerSettings&)’ to ‘void*’ [-Wpmf-conversions]
 Platform8pickFileER18FilePickerSettings", (void*) &LinuxAppPlatform::pickFile);
                                                                      ^
/home/peti/mcpelauncher-linux/src/LinuxAppPlatform.cpp:76:105: warning: converting from ‘bool (LinuxAppPlatform::*)()’ to ‘void*’ [-Wpmf-conversions]
 NK11AppPlatform19supportsFilePickingEv", (void*) &LinuxAppPlatform::supportsFil
                                                                     ^
/home/peti/mcpelauncher-linux/src/LinuxAppPlatform.cpp:77:115: warning: converting from ‘std::string& (LinuxAppPlatform::*)() {aka std::basic_string<char>& (LinuxAppPlatform::*)()}’ to ‘void*’ [-Wpmf-conversions]
 form_android22getExternalStoragePathEv", (void*) &LinuxAppPlatform::getExternal
                                                                     ^
/home/peti/mcpelauncher-linux/src/LinuxAppPlatform.cpp:78:115: warning: converting from ‘std::string& (LinuxAppPlatform::*)() {aka std::basic_string<char>& (LinuxAppPlatform::*)()}’ to ‘void*’ [-Wpmf-conversions]
 form_android22getInternalStoragePathEv", (void*) &LinuxAppPlatform::getInternal
                                                                     ^
/home/peti/mcpelauncher-linux/src/LinuxAppPlatform.cpp:79:114: warning: converting from ‘std::string& (LinuxAppPlatform::*)() {aka std::basic_string<char>& (LinuxAppPlatform::*)()}’ to ‘void*’ [-Wpmf-conversions]
 tform_android21getCurrentStoragePathEv", (void*) &LinuxAppPlatform::getCurrentS
                                                                     ^
/home/peti/mcpelauncher-linux/src/LinuxAppPlatform.cpp:80:108: warning: converting from ‘std::string& (LinuxAppPlatform::*)() {aka std::basic_string<char>& (LinuxAppPlatform::*)()}’ to ‘void*’ [-Wpmf-conversions]
 AppPlatform_android15getUserdataPathEv", (void*) &LinuxAppPlatform::getUserdata
                                                                     ^
/home/peti/mcpelauncher-linux/src/LinuxAppPlatform.cpp:81:117: warning: converting from ‘std::string& (LinuxAppPlatform::*)() {aka std::basic_string<char>& (LinuxAppPlatform::*)()}’ to ‘void*’ [-Wpmf-conversions]
 rm_android24getUserdataPathForLevelsEv", (void*) &LinuxAppPlatform::getUserdata
                                                                     ^
/home/peti/mcpelauncher-linux/src/LinuxAppPlatform.cpp:82:108: warning: converting from ‘std::string (LinuxAppPlatform::*)(const string&) {aka std::basic_string<char> (LinuxAppPlatform::*)(const std::basic_string<char>&)}’ to ‘void*’ [-Wpmf-conversions]
 AppPlatform20getAssetFileFullPathERKSs", (void*) &LinuxAppPlatform::getAssetFil
                                                                     ^
/home/peti/mcpelauncher-linux/src/LinuxAppPlatform.cpp:83:100: warning: converting from ‘bool (LinuxAppPlatform::*)()’ to ‘void*’ [-Wpmf-conversions]
 , "_ZNK11AppPlatform14useCenteredGUIEv", (void*) &LinuxAppPlatform::useCentered
                                                                     ^
/home/peti/mcpelauncher-linux/src/LinuxAppPlatform.cpp:84:109: warning: converting from ‘std::string (LinuxAppPlatform::*)() {aka std::basic_string<char> (LinuxAppPlatform::*)()}’ to ‘void*’ [-Wpmf-conversions]
 ppPlatform_android16getApplicationIdEv", (void*) &LinuxAppPlatform::getApplicat
                                                                     ^
/home/peti/mcpelauncher-linux/src/LinuxAppPlatform.cpp:85:111: warning: converting from ‘long long int (LinuxAppPlatform::*)()’ to ‘void*’ [-Wpmf-conversions]
 Platform_android18getAvailableMemoryEv", (void*) &LinuxAppPlatform::getAvailabl
                                                                     ^
/home/peti/mcpelauncher-linux/src/LinuxAppPlatform.cpp:86:104: warning: converting from ‘std::string (LinuxAppPlatform::*)() {aka std::basic_string<char> (LinuxAppPlatform::*)()}’ to ‘void*’ [-Wpmf-conversions]
 ZN19AppPlatform_android11getDeviceIdEv", (void*) &LinuxAppPlatform::getDeviceId
                                                                     ^
/home/peti/mcpelauncher-linux/src/LinuxAppPlatform.cpp:87:103: warning: converting from ‘std::string (LinuxAppPlatform::*)() {aka std::basic_string<char> (LinuxAppPlatform::*)()}’ to ‘void*’ [-Wpmf-conversions]
 _ZN19AppPlatform_android10createUUIDEv", (void*) &LinuxAppPlatform::createUUID)
                                                                     ^
/home/peti/mcpelauncher-linux/src/LinuxAppPlatform.cpp:88:111: warning: converting from ‘bool (LinuxAppPlatform::*)()’ to ‘void*’ [-Wpmf-conversions]
 Platform_android18isFirstSnoopLaunchEv", (void*) &LinuxAppPlatform::isFirstSnoo
                                                                     ^
/home/peti/mcpelauncher-linux/src/LinuxAppPlatform.cpp:89:122: warning: converting from ‘bool (LinuxAppPlatform::*)()’ to ‘void*’ [-Wpmf-conversions]
 droid29hasHardwareInformationChangedEv", (void*) &LinuxAppPlatform::hasHardware
                                                                     ^
/home/peti/mcpelauncher-linux/src/LinuxAppPlatform.cpp:90:100: warning: converting from ‘bool (LinuxAppPlatform::*)()’ to ‘void*’ [-Wpmf-conversions]
 a, "_ZN19AppPlatform_android8isTabletEv", (void*) &LinuxAppPlatform::isTablet);
                                                                      ^
/home/peti/mcpelauncher-linux/src/LinuxAppPlatform.cpp:91:117: warning: converting from ‘void (LinuxAppPlatform::*)(int)’ to ‘void*’ [-Wpmf-conversions]
 rm17setFullscreenModeE14FullscreenMode", (void*) &LinuxAppPlatform::setFullscre
                                                                     ^
/home/peti/mcpelauncher-linux/src/LinuxAppPlatform.cpp:92:96: warning: converting from ‘std::string (LinuxAppPlatform::*)() {aka std::basic_string<char> (LinuxAppPlatform::*)()}’ to ‘void*’ [-Wpmf-conversions]
  vta, "_ZNK11AppPlatform10getEditionEv", (void*) &LinuxAppPlatform::getEdition)
                                                                     ^
/home/peti/mcpelauncher-linux/src/LinuxAppPlatform.cpp:93:127: warning: converting from ‘long long int (LinuxAppPlatform::*)()’ to ‘void*’ [-Wpmf-conversions]
 31calculateAvailableDiskFreeSpaceERKSs", (void*) &LinuxAppPlatform::calculateAv
                                                                     ^
/home/peti/mcpelauncher-linux/src/LinuxAppPlatform.cpp:94:119: warning: converting from ‘int (LinuxAppPlatform::*)()’ to ‘void*’ [-Wpmf-conversions]
 m_android25getPlatformUIScalingRulesEv", (void*) &LinuxAppPlatform::getPlatform
                                                                     ^
/home/peti/mcpelauncher-linux/src/LinuxAppPlatform.cpp:95:112: warning: converting from ‘std::string& (LinuxAppPlatform::*)() {aka std::basic_string<char>& (LinuxAppPlatform::*)()}’ to ‘void*’ [-Wpmf-conversions]
 latform_android19getPlatformTempPathEv", (void*) &LinuxAppPlatform::getPlatform
                                                                     ^
/home/peti/mcpelauncher-linux/src/LinuxAppPlatform.cpp:96:107: warning: converting from ‘std::string (LinuxAppPlatform::*)() {aka std::basic_string<char> (LinuxAppPlatform::*)()}’ to ‘void*’ [-Wpmf-conversions]
 9AppPlatform_android14createDeviceIDEv", (void*) &LinuxAppPlatform::createDevic
                                                                     ^
[ 95%] Building CXX object CMakeFiles/mcpelauncher.dir/mcpe/types.cpp.o
[100%] Linking CXX executable mcpelauncher
CMakeFiles/mcpelauncher.dir/hybris/src/hooks.c.o: In function `my_pthread_attr_getstackaddr':
hooks.c:(.text+0x3f8): warning: the use of `pthread_attr_getstackaddr' is deprecated, use `pthread_attr_getstack'
CMakeFiles/mcpelauncher.dir/hybris/src/hooks.c.o: In function `my_pthread_attr_setstackaddr':
hooks.c:(.text+0x3d7): warning: the use of `pthread_attr_setstackaddr' is deprecated, use `pthread_attr_setstack'
/usr/bin/ld: cannot find -lX11
/usr/bin/ld: cannot find -luuid
collect2: error: ld returned 1 exit status
CMakeFiles/mcpelauncher.dir/build.make:607: recipe for target 'mcpelauncher' failed
make[2]: *** [mcpelauncher] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/mcpelauncher.dir/all' failed
make[1]: *** [CMakeFiles/mcpelauncher.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

Cmake works fine. Any solution?

**Comment by guppy42** [comment]
```
/usr/bin/ld: cannot find -lX11
/usr/bin/ld: cannot find -luuid
```

Tells you all you need tbh.

https://github.com/MCMrARM/mcpelauncher-linux/wiki/Installation-guide#preparation-and-required-packages

I'm guessing libuuid is a requirement of libx11-dev if not;

`sudo apt install libx11-dev libuuid `

should solve it

**Comment by SlimePharaoh** [comment]
Of course I already installed the required packages, also the libx11-dev and the libuuid1 (libuuid doesn't exist) package, the problem is still the same. The libx11-dev:i386 and the libuuid1:i386 didn't help either.

**Comment by windo** [comment]
Did do a fresh cmake setup after installing the packages?

You may be correct on the :i386 variants on the dev packages though. I had to explicitly install libgles2-mesa-dev:i386 and libegl1-mesa-dev:i386 on top of the official required package list to make the build work.

**Comment by Dhrhciebcy** [comment]
sudo apt-get install libgles2-mesa-dev:i386 libegl1-mesa-dev:i386 libmirclient-dev:i386 libwayland-dev:i386 libmircommon-dev:i386 libxkbcommon-dev:i386

worked for me
